ROLE_PERMISSIONS: dict[str, set[str]] = {
    "super_admin": {
        "admin.dashboard",
        "identities.read",
        "identities.write",
        "systems.read",
        "systems.write",
        "resources.read",
        "resources.write",
        "task_mappings.read",
        "task_mappings.write",
        "requests.read",
        "requests.write",
        "approvals.read",
        "approvals.decide",
        "provisioning.read",
        "provisioning.complete",
        "assignments.read",
        "delegations.read",
        "delegations.write",
        "audit.read",
        "emergency_termination.execute",
        "governance.read",
        "governance.write",
        "reconciliation.read",
        "reconciliation.execute",
        "certifications.read",
        "certifications.write",
        "certifications.decide",
        "pam.vault.read",
        "pam.vault.admin",
        "pam.checkout",
        "pam.break_glass",
        "connectors.read",
        "connectors.write",
        "connectors.execute",
        "scim.read",
        "scim.write",
        "jobs.read",
        "jobs.write",
        "jobs.execute",
    },
    "manager": {
        "requests.read",
        "requests.write",
        "approvals.read",
        "approvals.decide",
        "assignments.read",
        "delegations.read",
        "delegations.write",
        "certifications.read",
        "certifications.decide",
        "pam.checkout",
    },
    "operator": {
        "requests.read",
        "provisioning.read",
        "provisioning.complete",
        "assignments.read",
        "audit.read",
        "reconciliation.read",
        "certifications.read",
        "pam.vault.read",
        "connectors.read",
        "jobs.read",
        "jobs.execute",
    },
    "employee": {
        "requests.read",
        "requests.write",
        "assignments.read",
        "delegations.read",
        "certifications.read",
        "certifications.decide",
        "pam.checkout",
    },
}


def permissions_for_role(role: str) -> list[str]:
    return sorted(ROLE_PERMISSIONS.get(role, set()))


def require_permission(role: str, permission: str) -> bool:
    return permission in ROLE_PERMISSIONS.get(role, set())
